IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_POSTS')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_POSTS', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_COMMENTS')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_COMMENTS', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_EVENTS')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_EVENTS', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_LEADERBOARD')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_LEADERBOARD', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_NOTIFICATIONS')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_NOTIFICATIONS', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_PROFILE')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_PROFILE', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_MEALPLAN')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_MEALPLAN', '0', GETDATE());
END;

IF NOT EXISTS (SELECT 1 FROM SystemSetting WHERE [key] = 'MAINTENANCE_MODULE_AI')
BEGIN
    INSERT INTO SystemSetting([key], [value], updatedAt)
    VALUES ('MAINTENANCE_MODULE_AI', '0', GETDATE());
END;