diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=tvghung@gmail.com
user.name=tvghung
user.mail=tvghung@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/Khanh179207/DATN-CD.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
branch.develop.vscode-merge-base=origin/develop
branch.feature/Fix-UI/UX-+-Update-BackEnd-All.remote=origin
branch.feature/Fix-UI/UX-+-Update-BackEnd-All.merge=refs/heads/feature/Fix-UI/UX-+-Update-BackEnd-All
branch.feature/Fix-UI/UX-+-Update-BackEnd-All.vscode-merge-base=origin/feature/Fix-UI/UX-+-Update-BackEnd-All
branch.feature/phan-quyen.vscode-merge-base=origin/develop
