package poly.edu.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

import java.util.List;

@Data
public class TotpEnableRequestDTO {
    /**
     * TOTP code generated by the authenticator app after scanning the QR code.
     * Must be valid before we persist and activate the secret.
     */
    @NotBlank(message = "totpCode is required")
    private String totpCode;

    /** The pending secret sent in the setup response (client echoes it back). */
    @NotBlank(message = "secret is required")
    private String secret;

    /**
     * The backup codes returned by the /mfa/setup endpoint.
     * The client must echo them back; they are then persisted as hashes.
     */
    @NotEmpty(message = "backupCodes are required")
    private List<String> backupCodes;
}
