spring.application.name=GoMet-BE

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATN_CD;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto=none

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# App config
app.base-url=http://localhost:8080
app.frontend.url=http://localhost:5173
app.allowed-origins=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khanhdcmts00903@fpt.edu.vn
spring.mail.password=fzgqgrrnvnoetahe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com