    # ==========================================
    # 1. SPRING APPLICATION CONFIGURATION
    # ==========================================
    spring.application.name=GoMet-BE
    spring.devtools.restart.enabled=false

    # ==========================================
    #  DATABASE SQL OFFLINE
    # ==========================================

    spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DATN_CD;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;useUnicode=true;characterEncoding=UTF-8
    spring.datasource.username=sa
    spring.datasource.password=12345678
    spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

    # ==========================================
    # 2. DATABASE CONFIGURATION (SOMEE ONLINE)
    # ==========================================
#    spring.datasource.url=jdbc:sqlserver://Gomet_DB2026.mssql.somee.com;databaseName=Gomet_DB2026;encrypt=true;trustServerCertificate=true;
#    spring.datasource.username=gomet
#    spring.datasource.password=gomet@123
#    spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#    # Hibernate Configuration
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # ==========================================
    # 3. SECURITY & LOGGING
    # ==========================================
    logging.level.org.springframework.security=DEBUG

    # ==========================================
    # 4. FILE UPLOAD CONFIGURATION (MULTIPART)
    # ==========================================
    spring.servlet.multipart.enabled=true
    spring.servlet.multipart.max-file-size=20MB
    spring.servlet.multipart.max-request-size=25MB

    # ==========================================
    # 5. CORS & APP URL CONFIGURATION
    # ==========================================
    app.base-url=http://localhost:8080
    app.frontend.url=http://localhost:5173
    app.allowed-origins=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173

    # ==========================================
    # 6. EMAIL CONFIGURATION (SMTP GMAIL)
    # ==========================================
    spring.mail.host=smtp.gmail.com
    spring.mail.port=587
    spring.mail.username=khanhdcmts00903@fpt.edu.vn
    spring.mail.password=fzgqgrrnvnoetahe
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.starttls.enable=true
    spring.mail.properties.mail.smtp.starttls.required=true
    spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# GOOGLE AUTH
google.client.id=234763019792-mvr72fupigk7aq9ieuf29thfotcla00c.apps.googleusercontent.com
    # ==========================================
    # 7. CLOUD STORAGE (CLOUDINARY)
    # ==========================================
    cloudinary.cloud-name=drblrjxan
    cloudinary.api-key=622827797465398
    cloudinary.api-secret=pEwpIlUEudyMUZWqJ01yzG4b0wU
